- name: configure apt proxy
  template:
    src: proxy.j2
    dest: /etc/apt/apt.conf.d/00proxy
  notify:
    - update apt cache
  tags:
    - install

- meta: flush_handlers

- name: update apt cache if stale
  apt:
    update_cache: yes
    cache_valid_time: 7200
  tags:
    - install
